name: bizitme
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0


  http: ^0.13.0
  fluttertoast: ^8.0.4
  shared_preferences: ^0.5.4+1
  cached_network_image: ^2.5.0
  intl: ^0.17.0
  image_picker: ^0.7.0

  firebase_storage: ^8.0.4
  firebase_messaging: ^10.0.0

  flutter_local_notifications: ^9.4.0
  photo_view: ^0.14.0
  cloud_firestore: ^3.1.9

  firebase_core: ^1.1.0
  image_crop: ^0.4.0
  flutter_image_compress: ^0.6.5+1
  flutter_webview_plugin: ^0.3.11
  url_launcher: ^6.0.3
#  location: ^4.0.0 # change this
  keyboard_actions: ^3.3.1+1

  google_maps_flutter: ^2.0.6
  flutter_spinkit: ^4.1.2+1
  flutter_staggered_animations: "^0.1.2"
  animate_do: ^1.7.3
  double_back_to_close_app: 2.0.1
  pin_entry_text_field: ^0.1.4
  image_cropper: ^1.4.0
  numberpicker: ^1.3.0
  jiffy: 4.1.0


  auto_size_text: ^2.1.0
#  place_picker: ^0.9.16   change this
  firebase_auth: ^1.3.0
  carousel_pro: ^1.0.0
  date_format: ^1.0.9
  date_time_picker: ^2.0.0
  flutter_calendar_carousel: ^1.4.12
  flushbar: 1.10.4
  country_calling_code_picker: ^1.0.8+1
  country_code_picker: ^1.7.0
  flutter_rating: ^0.0.2
  geocoder: ^0.2.1

#  stripe_payment: ^1.1.4
#  flutter_stripe: ^1.0.1


  google_places_picker: ^3.0.2

  geolocator: ^7.1.0

  google_maps_webservice: 0.0.20-nullsafety.0

  provider: ^5.0.0
  tuple: ^2.0.0
  permission_handler: ^8.1.2
  google_api_headers: ^1.1.0


  stripe_payment: ^1.0.10


dependency_overrides:
  firebase_messaging_platform_interface: 3.1.6
  cloud_firestore_platform_interface: 5.4.11




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material ..Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Images/
    - assets/Images/per_week.png
    - assets/Images/per_day.png
    - assets/Images/chatsendimg.png
    - assets/Images/checkicon_payment.png
    - assets/Images/uncheckicon_payment.png
    - assets/audio/notification_sound.mp3


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat-Thin.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
